[theme]
# Colores institucionales EAFIT
primaryColor = "#F7B500"       # Amarillo EAFIT
backgroundColor = "#FFFFFF"    # Fondo blanco
secondaryBackgroundColor = "#F0F2F6"  # Gris claro
textColor = "#001E62"          # Azul EAFIT
font = "sans serif"

[server]
maxUploadSize = 200
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[logger]
level = "error"
